# Generated by Django 3.2.9 on 2021-12-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtuber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtuber',
            name='channelId',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
