# Generated by Django 3.2.9 on 2021-12-12 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtuber', '0002_youtuber_channelid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtuber',
            old_name='channelId',
            new_name='channel_id',
        ),
    ]
